//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EscuelaMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calificacion
    {
        public int ID_Calificacion { get; set; }
        public double Calificacion1 { get; set; }
        public int ID_Estudiante { get; set; }
        public int ID_Asignatura { get; set; }
    
        public virtual Asignatura Asignatura { get; set; }
        public virtual Estudiante Estudiante { get; set; }
    }
}
